# Generated by Django 3.2.8 on 2021-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source_code_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
