# Generated by Django 3.2.8 on 2021-10-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20211006_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientorg",
            name="testimonial",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
