# Generated by Django 3.2.8 on 2021-10-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_project_storyboard"),
        ("portal", "0004_alter_clientorg_testimonial"),
    ]

    operations = []
