# Generated by Django 3.2.8 on 2021-11-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_project_client_org"),
        ("portal", "0005_merge_20211028_1701"),
    ]

    operations = []
