# Generated by Django 3.2.8 on 2021-10-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_merge_20211028_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
