# Generated by Django 3.2.8 on 2021-11-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_user_activation_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
