# Generated by Django 3.2.8 on 2021-11-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_auto_20211102_2035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorg",
            name="image",
            field=models.ImageField(null=True, upload_to="client_orgs/org_image/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="logo_image",
            field=models.ImageField(null=True, upload_to="projects/logo_image/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="users/user_image/"),
        ),
    ]
