# Generated by Django 3.2.8 on 2021-11-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_user_activation_key"),
        ("portal", "0007_auto_20211102_2302"),
    ]

    operations = []
