# Generated by Django 3.2.9 on 2021-11-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_merge_20211108_2047"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="screenshot",
        ),
    ]
