# Generated by Django 3.2.9 on 2021-11-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_merge_20211108_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorg",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="client_orgs/org_image/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="logo_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/logo_image/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/user_image/"
            ),
        ),
    ]
