# Generated by Django 3.2.9 on 2021-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_remove_project_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="screenshot",
            field=models.ImageField(null=True, upload_to="projects/screenshot/"),
        ),
    ]
