# Generated by Django 3.2.9 on 2021-11-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_auto_20211111_1157"),
        ("portal", "0010_project_screenshot"),
    ]

    operations = []
