# Generated by Django 3.2.9 on 2021-11-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_merge_20211031_2016"),
        ("portal", "0010_project_screenshot"),
    ]

    operations = []
