# Generated by Django 3.2.8 on 2021-11-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_passwordresetrequest"),
        ("portal", "0012_alter_project_screenshot"),
    ]

    operations = []
