# Generated by Django 4.0b1 on 2021-11-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_merge_20211112_0124"),
        ("portal", "0013_merge_20211113_1022"),
    ]

    operations = []
