# Generated by Django 3.2.9 on 2021-11-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_merge_20211113_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
        migrations.AlterField(
            model_name="clientorg",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
