# Generated by Django 3.2.9 on 2021-11-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_project_display_on_home_page"),
        ("portal", "0016_remove_clientorg_logo"),
    ]

    operations = []
