name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install NPM packages
        working-directory: ./frontend
        run: npm install
      - name: Run ESLint
        working-directory: ./frontend
        run: npx eslint . --max-warnings 0

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install NPM packages
        working-directory: ./frontend
        run: npm install
      - name: Run Prettier
        working-directory: ./frontend
        run: npx prettier --check .

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install NPM packages
        working-directory: ./frontend
        run: npm install
      - name: Compile TypeScript
        working-directory: ./frontend
        run: npx tsc --noEmit

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install NPM packages
        run: npm install
      - name: Execute the tests
        run: CHROME_BINARY_PATH=$(which chrome) npm test
